import { notFound } from "next/navigation";
import { WorkspacePage } from "@/components/journey-workspace";
import { ArrowRight, BookOpen, Building2, ClipboardList, GraduationCap, Route, Scale } from "lucide-react";
import { Badge, BulletList, ButtonLink, Callout, Disclosure, accentSurface, type Accent } from "@/components/ui";
import { SaveButton } from "@/components/save-button";
import { DetailTabs } from "@/components/detail-tabs";
import { DetailHeader, LinkRow, MiniJourney, NextStepPanel } from "@/components/detail-parts";
import { getCourses, getExams, getField, getInstitutionsForCourse, getPathway } from "@/services/catalog";
import { getSessionState } from "@/services/profile";
import { whatIfScenarios } from "@/recommendation/engine";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { return { title: (await getPathway((await params).slug))?.title ?? "Pathway" }; }
export default async function PathwayPage({ params }: { params: Promise<{ slug: string }> }) {
  const pathway = await getPathway((await params).slug); if (!pathway) notFound();
  const [courses, exams, field, state] = await Promise.all([getCourses({ slugs: pathway.courseSlugs ?? [] }), getExams({ slugs: pathway.examSlugs ?? [] }), pathway.fieldSlug ? getField(pathway.fieldSlug) : Promise.resolve(null), getSessionState()]);
  const lists = await Promise.all(courses.map((c) => getInstitutionsForCourse(c.slug)));
  const institutions = [...new Map(lists.flat().map((i) => [i.code, i])).values()];
  const scenarios = whatIfScenarios(field, state?.snapshot);
  const shortTitle = pathway.title.split("→").slice(1).join(" → ").trim() || pathway.title;
  const accents: Accent[] = ["mint", "butter", "lavender", "sky"];
  const routeContent = <section className="cb-panel"><h2 className="cb-panel-title"><Route />Your route, one step at a time</h2><p className="mb-6 text-sm text-ink-500">Tap a step to see what it involves.</p><ol className="relative space-y-4 border-l-2 border-dashed border-forest-200 pl-6">{(pathway.steps ?? []).map((step, i) => <li key={step.label} className="relative pl-2"><span aria-hidden className={`absolute -left-10 top-3 grid h-8 w-8 place-items-center rounded-full border-4 border-white text-xs font-bold ${accentSurface[accents[i % 4]]}`}>{i + 1}</span><Disclosure summary={step.label} hint={i === 0 ? "Start here" : undefined} defaultOpen={i === 0}><p>{step.detail}</p></Disclosure></li>)}</ol>{pathway.notes && <div className="mt-6"><Callout tone="forest" title="Worth knowing"><p>{pathway.notes}</p></Callout></div>}</section>;
  const courseContent = <div className="space-y-4"><section className="cb-panel"><h2 className="cb-panel-title"><GraduationCap />Courses along this route</h2><div className="space-y-3">{courses.map((c) => <LinkRow key={c.slug} href={`/courses/${c.slug}`} title={c.name} description={c.durationLabel} icon={<GraduationCap className="h-4 w-4" />} accent="lavender" action="View course" />)}{!courses.length && <p className="text-sm text-ink-500">No courses are mapped yet. Browse the course catalogue to explore.</p>}</div></section><Disclosure summary="Entrance examinations"><div className="space-y-3">{exams.map((e) => <LinkRow key={e.slug} href={`/exams#${e.slug}`} title={e.shortName ?? e.name} description="Requirements and official dates" icon={<BookOpen className="h-4 w-4" />} action="Check exam" />)}{!exams.length && <p>No exam is listed for this route. Confirm the requirements with the institution.</p>}</div></Disclosure><Disclosure summary={`Where could I study? (${institutions.length})`} hint="Sample listings"><Badge tone="amber">Needs verification</Badge><div className="mt-4 space-y-3">{institutions.map((i) => <LinkRow key={i.code} href={`/institutions/${i.code}`} title={i.name} description={i.district} icon={<Building2 className="h-4 w-4" />} accent="sky" action="View institution" />)}</div></Disclosure></div>;
  const reflect = <div className="space-y-4"><Disclosure summary="Why might this route NOT suit me?" tone="amber"><BulletList items={[...(field?.challenges ?? []), "Check the total time and cost, including living and travel expenses."]} /></Disclosure>{scenarios.map((scenario) => <Disclosure key={scenario.key} summary={scenario.question}><p className="mb-3">{scenario.answer}</p><BulletList items={scenario.suggestions} /></Disclosure>)}</div>;
  return <WorkspacePage active="pathways"><div className="mb-5"><MiniJourney current={1} /></div><DetailHeader eyebrow={`After ${pathway.entryStage === "class10" ? "Class 10" : "Class 12"} · ${pathway.routeType} route`} title={shortTitle} description={pathway.description} icon={<Route className="h-6 w-6" />} accent="butter" facts={pathway.typicalDuration ? <Badge tone="amber">Typical duration: {pathway.typicalDuration}</Badge> : null} actions={<><ButtonLink href={`/action-plan?focus=pathway:${pathway.slug}`}><ClipboardList aria-hidden className="h-4 w-4" />Build my action plan</ButtonLink><SaveButton itemType="pathway" itemRef={pathway.slug} label={pathway.title} /><ButtonLink href={`/compare?type=pathway&a=${pathway.slug}`} variant="secondary"><Scale aria-hidden className="h-4 w-4" />Compare routes</ButtonLink></>} />
    <div className="cb-detail-content"><DetailTabs tabs={[{ id: "overview", icon: "pathways", label: "The journey", content: routeContent }, { id: "courses", label: "Courses & institutions", content: courseContent }, { id: "reflect", label: "What if?", content: reflect }]} /><aside className="cb-detail-aside"><NextStepPanel title="A direction, not a final decision." text="Keep the route, check requirements, and shortlist courses. You can change your plan later." href={`/action-plan?focus=pathway:${pathway.slug}`} cta="Make my checklist" />{field && <LinkRow href={`/explore/${field.slug}`} title={field.name} description="Revisit the field behind this pathway" icon={<Route className="h-4 w-4" />} action="Explore" />}<ButtonLink href={`/pathways?stage=${pathway.entryStage}`} variant="secondary">See other routes<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink></aside></div>
  </WorkspacePage>;
}
