import { notFound } from "next/navigation";
import { WorkspacePage } from "@/components/journey-workspace";
import { ArrowRight, BookOpen, BriefcaseBusiness, Building2, GraduationCap, Lightbulb, Route, Scale, ShieldCheck } from "lucide-react";
import { Badge, BulletList, ButtonLink, Callout, Disclosure, StepList } from "@/components/ui";
import { SaveButton } from "@/components/save-button";
import { DetailTabs } from "@/components/detail-tabs";
import { DetailHeader, LinkRow, NextStepPanel, NoCatalogItems } from "@/components/detail-parts";
import { FieldIcon, fieldVisual } from "@/components/field-visuals";
import { getCareer, getCareerSkills, getCareers, getCourses, getExams, getField, getInstitutionsForCourse, getPathways } from "@/services/catalog";
import { getSessionState } from "@/services/profile";
import { whatIfScenarios } from "@/recommendation/engine";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { return { title: (await getCareer((await params).slug))?.title ?? "Career" }; }
export default async function CareerPage({ params }: { params: Promise<{ slug: string }> }) {
  const career = await getCareer((await params).slug); if (!career) notFound();
  const [field, skills, courses, exams, allPaths, related, state] = await Promise.all([getField(career.fieldSlug), getCareerSkills(career.slug), getCourses({ slugs: career.courseSlugs ?? [] }), getExams({ slugs: career.examSlugs ?? [] }), getPathways({}), getCareers(career.fieldSlug), getSessionState()]);
  const paths = allPaths.filter((p) => (career.pathwaySlugs ?? []).includes(p.slug));
  const linkedInstitutions = await Promise.all(courses.map((c) => getInstitutionsForCourse(c.slug)));
  const institutions = [...new Map(linkedInstitutions.flat().map((i) => [i.code, i])).values()];
  const scenarios = whatIfScenarios(field, state?.snapshot);
  const overview = <div className="space-y-5"><section className="cb-panel"><h2 className="cb-panel-title"><BriefcaseBusiness />What the work looks like</h2><BulletList items={career.whatItInvolves ?? []} /></section><div className="grid gap-4 sm:grid-cols-2"><section className="rounded-xl border border-sky-ink/20 bg-sky/35 p-5"><h3 className="cb-panel-title"><BookOpen />Helpful subjects</h3><div className="flex flex-wrap gap-2">{(career.subjects ?? []).map((s) => <Badge key={s}>{s}</Badge>)}</div></section><section className="rounded-xl border border-butter-ink/20 bg-butter/30 p-5"><h3 className="cb-panel-title"><Building2 />Where people work</h3><BulletList items={career.workContexts ?? []} /></section></div><Disclosure summary="What can progression look like?"><StepList items={(career.progression ?? []).map((step) => ({ title: step, detail: "One possible stage — progression varies by role and employer." }))} /></Disclosure></div>;
  const skillContent = <section className="cb-panel"><h2 className="cb-panel-title"><Lightbulb />Start building, little by little.</h2>{skills.length ? <div className="space-y-3">{skills.map((s) => <Disclosure key={s.id} summary={s.skill} hint="How to practise"><p>{s.howToBuild ?? "Look for a small project that lets you practise this skill."}</p></Disclosure>)}</div> : <BulletList items={field?.skills ?? []} />}<ButtonLink href={`/opportunities?field=${career.fieldSlug}`} className="mt-6">Find learning opportunities<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink></section>;
  const study = <div className="space-y-4"><section className="cb-panel"><h2 className="cb-panel-title"><Route />Routes into this work</h2><p className="cb-measure mb-5 text-sm leading-relaxed text-ink-600">{career.entryEducation ?? "Entry requirements depend on the role."}</p><div className="space-y-3">{paths.map((p) => <LinkRow key={p.slug} href={`/pathways/${p.slug}`} title={p.title} description={p.typicalDuration} icon={<Route className="h-4 w-4" />} accent="butter" action="View route" />)}{!paths.length && <NoCatalogItems href="/pathways" label="Browse pathways" />}</div></section><Disclosure summary={`Courses (${courses.length})`}><div className="space-y-3">{courses.map((c) => <LinkRow key={c.slug} href={`/courses/${c.slug}`} title={c.name} description={c.durationLabel} icon={<GraduationCap className="h-4 w-4" />} accent="lavender" />)}</div></Disclosure><Disclosure summary={`Institutions in Nagaland (${institutions.length})`} hint="Sample links — verify course availability"><div className="mb-4"><Badge tone="amber">Sample data</Badge></div><div className="space-y-3">{institutions.map((i) => <LinkRow key={i.code} href={`/institutions/${i.code}`} title={i.name} description={i.district} icon={<Building2 className="h-4 w-4" />} accent="sky" />)}</div></Disclosure><Disclosure summary="Entrance examinations"><div className="space-y-3">{exams.map((e) => <LinkRow key={e.slug} href={`/exams#${e.slug}`} title={e.shortName ?? e.name} description="Requirements and official portal" action="Check exam" />)}{!exams.length && <p>No examination is linked in our catalogue. Confirm the requirements for your chosen course.</p>}</div></Disclosure></div>;
  const reflect = <div className="space-y-3"><Disclosure summary="Why might this NOT be right for me?" tone="amber"><BulletList items={career.challenges ?? []} /></Disclosure><Disclosure summary="Questions to ask myself"><BulletList items={career.questionsToConsider ?? []} /></Disclosure><Disclosure summary="Are there other routes in?"><BulletList items={career.alternativeRoutes ?? []} /></Disclosure><Disclosure summary="What if my circumstances change?"><div className="space-y-3">{scenarios.map((s) => <Disclosure key={s.key} summary={s.question}><p className="mb-3">{s.answer}</p><BulletList items={s.suggestions} /></Disclosure>)}</div></Disclosure><section className="cb-panel"><h2 className="cb-panel-title"><Scale />Compare related work</h2><div className="space-y-3">{related.filter((c) => c.slug !== career.slug).map((c) => <LinkRow key={c.slug} href={`/compare?type=career&a=${career.slug}&b=${c.slug}`} title={c.title} description={c.summary} icon={<Scale className="h-4 w-4" />} accent="lavender" action="Compare" />)}</div></section></div>;
  return <WorkspacePage active="explore"><DetailHeader eyebrow={field?.name ?? "Explore a career"} title={career.title} description={career.summary} icon={<FieldIcon slug={career.fieldSlug} className="h-6 w-6" />} accent={fieldVisual(career.fieldSlug).accent} actions={<><ButtonLink href={`/pathways?field=${career.fieldSlug}`}>Explore pathways<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink><SaveButton itemType="career" itemRef={career.slug} label={career.title} /><ButtonLink href={`/compare?type=career&a=${career.slug}`} variant="secondary"><Scale aria-hidden className="h-4 w-4" />Compare careers</ButtonLink></>} />
    <div className="cb-detail-content"><DetailTabs tabs={[{ id: "overview", label: "The work", content: overview }, { id: "skills", icon: "courses", label: "Skills", content: skillContent }, { id: "pathways", label: "How to get there", content: study }, { id: "reflect", label: "Is it for me?", content: reflect }]} /><aside className="cb-detail-aside"><NextStepPanel title="Find a route that works for you." text="See the different education options before deciding on a course." href={`/pathways?field=${career.fieldSlug}`} cta="Explore study routes" mentorQuestion={`What should I consider before exploring ${career.title}?`} /><Callout icon={<ShieldCheck className="h-4 w-4" />} title="About this guidance"><p>Career descriptions are general guidance. Course and institution pages include their own source and verification details.</p></Callout><ButtonLink href={`/action-plan?focus=career:${career.slug}`} variant="secondary">Build an action plan<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink></aside></div>
  </WorkspacePage>;
}
