import Link from "next/link";
import { ArrowRight, BookOpenCheck, CalendarDays, FileText, ShieldCheck } from "lucide-react";
import { Badge, Disclosure, SourceLink, VerificationBadge } from "@/components/ui";
import { SaveButton } from "@/components/save-button";
import { getExams } from "@/services/catalog";
import { WorkspacePage } from "@/components/journey-workspace";
export const dynamic = "force-dynamic";
export const metadata = { title: "Entrance examinations" };
export default async function ExamsPage() { const exams = await getExams(); return <WorkspacePage active="plan"><div className="concept-page-header"><div><p className="concept-kicker">Before you apply</p><h1 className="concept-title">Know the next requirement.</h1><p className="concept-subtitle">Find the exam, understand what it opens, and check the current official notice.</p></div><BookOpenCheck className="hidden h-14 w-14 text-sky-ink sm:block" /></div><div className="mb-5 flex items-center gap-2 rounded-xl bg-butter/55 px-4 py-3 text-xs font-semibold text-butter-ink"><CalendarDays className="h-4 w-4" />Dates change each cycle. Always check the official notice.</div><div className="concept-soft-panel divide-y divide-ink-100 px-5">{exams.map((exam) => <article key={exam.slug} className="py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky text-sky-ink"><FileText className="h-5 w-5" /></span><div><h2 className="text-lg font-bold text-ink-900">{exam.name}</h2><p className="mt-1 text-xs text-ink-500">{exam.conductingBody}</p></div></div><VerificationBadge status={exam.verificationStatus} lastVerifiedAt={exam.lastVerifiedAt} /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-ink-600">{(exam.appliesTo ?? []).join(" · ")}</p><div className="flex flex-wrap gap-2"><SourceLink href={exam.officialWebsite}>Official site</SourceLink><SaveButton itemType="exam" itemRef={exam.slug} label={exam.shortName ?? exam.name} /></div></div><Disclosure summary="Eligibility and how to prepare"><p>{exam.eligibility ?? "Currently unavailable."}</p><p className="mt-3 text-sm">{(exam.preparation ?? []).join(" ")}</p></Disclosure></article>)}</div><div className="mt-6 flex items-center gap-2 rounded-xl bg-mint/60 p-4 text-sm"><ShieldCheck className="h-4 w-4 text-forest-700" />The official notification takes priority over this outline.</div></WorkspacePage>; }
