import Link from "next/link";
import { ArrowRight, Check, ChevronRight, Compass, Edit3, Heart, MapPin, MessageCircle, Pencil, Sparkles, Target, Wallet } from "lucide-react";
import { ButtonLink, Callout, Disclosure, EmptyState, Eyebrow, Badge, accentSurface, type Accent } from "@/components/ui";
import { FieldIcon, fieldVisual } from "@/components/field-visuals";
import { FACTOR_LABELS, suggestFields, suggestPathways } from "@/recommendation/engine";
import { getSessionState, labelFor } from "@/services/profile";
import { optionalQuestionsForStage } from "@/data/counselling";

export const dynamic = "force-dynamic";
export const metadata = { title: "My possibilities" };

const answerLabels: Record<string, string> = { "home-district": "Near my district", "within-nagaland": "Within Nagaland", "outside-open": "Open to outside Nagaland", "not-sure": "Not sure yet", low: "Lower-fee options", moderate: "Moderate fees", flexible: "Flexible budget", unsure: "Budget not known yet", "with-people": "Working with people", independent: "Independent work", "hands-on": "Hands-on work", outdoors: "Outdoor work", mixed: "A mix" };
const optionalLabels: Record<string, string> = { subjects_difficult: "Difficult subjects", performance: "How studies are going", interest_story: "Something you enjoy", work_style: "Preferred work style", home_district: "Your district", scholarship_need: "Scholarship needs", institution_pref: "Institution preference", hostel: "Hostel needs", anything_else: "Anything else" };
const pretty = (value: string | null) => value ? answerLabels[value] ?? value.replace(/-/g, " ") : null;

type SummaryItem = { label: string; value: string[]; edit: string; accent: Accent; icon: typeof Heart };

export default async function ProfilePage() {
  const state = await getSessionState();
  if (!state) return <div className="cb-container cb-page"><EmptyState icon={<Compass className="h-5 w-5" />} title="Let’s find your starting points." description="A few short questions help us show possibilities that may be worth exploring." action={<ButtonLink href="/start">Start here<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink>} /></div>;
  const { snapshot } = state;
  const ready = snapshot.completion >= 100;
  const [fields, paths] = await Promise.all([suggestFields(snapshot, 4), suggestPathways(snapshot, 3)]);
  const summary: SummaryItem[] = [
    { label: "Subjects I enjoy", value: snapshot.subjectsEnjoy.map((s) => labelFor("subject", s)), edit: "subjects_enjoy", accent: "mint", icon: Sparkles },
    { label: "Things I’m curious about", value: snapshot.interests.map((s) => labelFor("interest", s)), edit: "interests", accent: "butter", icon: Heart },
    { label: "Things I’m good at", value: snapshot.strengths.map((s) => labelFor("strength", s)), edit: "strengths", accent: "lavender", icon: Target },
    { label: "What matters to me", value: snapshot.values.map((s) => labelFor("value", s)), edit: "values", accent: "peach", icon: Compass },
    { label: "Study preference", value: [pretty(snapshot.locationPref), snapshot.district].filter(Boolean) as string[], edit: "location_pref", accent: "sky", icon: MapPin },
    { label: "Fee preference", value: [pretty(snapshot.budget)].filter(Boolean) as string[], edit: "budget", accent: "mint", icon: Wallet },
  ];
  const optional = optionalQuestionsForStage(snapshot.stage);
  return <div className="cb-container cb-page">
    <header className="mb-5 overflow-hidden rounded-[1.5rem] border border-forest-200 bg-mint/65 p-6 sm:p-9">
      <div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><Eyebrow>Step 3 · My possibilities</Eyebrow><h1 className="mt-3 text-[clamp(2rem,4vw,3.5rem)] font-semibold leading-tight">Here are a few directions worth looking into.</h1><p className="mt-4 max-w-xl text-base leading-relaxed text-ink-600">These are not predictions and they are not a final answer. They are simply places to start exploring, based on what you told us.</p></div><span className="inline-flex items-center gap-2 rounded-xl border border-forest-200 bg-white px-4 py-3 text-sm font-semibold text-forest-800"><Check aria-hidden className="h-4 w-4" />{snapshot.stage === "class10" ? "Class 10" : "Class 12"}</span></div>
      <div className="mt-7 flex items-center gap-2 text-xs font-semibold text-forest-800"><span className="h-2 w-2 rounded-full bg-forest-700" />About me<span className="h-px w-8 bg-forest-300" /><span className="h-2 w-2 rounded-full bg-forest-700" />Possibilities<span className="h-px w-8 bg-forest-300" /><span className="h-2 w-2 rounded-full border border-forest-500 bg-white" />My next steps</div>
    </header>

    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.45fr)] lg:gap-9">
      <aside className="order-2 space-y-4 lg:order-1 lg:sticky lg:top-28">
        <section id="my-answers" className="rounded-2xl border border-ink-200 bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">What we heard</h2><p className="mt-1 text-sm text-ink-500">Your answers, not a test result.</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky text-sky-ink"><Edit3 aria-hidden className="h-5 w-5" /></span></div><div className="mt-4 divide-y divide-ink-100">{summary.map((item) => { const Icon = item.icon; return <div key={item.label} className="py-3"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-semibold text-ink-700"><span className={`grid h-7 w-7 place-items-center rounded-lg ${accentSurface[item.accent]}`}><Icon aria-hidden className="h-3.5 w-3.5" /></span>{item.label}</span><Link href={`/counselling?edit=${item.edit}`} aria-label={`Edit ${item.label}`} className="text-xs font-semibold text-forest-700 underline underline-offset-4">Edit</Link></div><div className="mt-2 pl-9">{item.value.length ? <div className="flex flex-wrap gap-1.5">{item.value.slice(0, 3).map((value) => <Badge key={value}>{value}</Badge>)}</div> : <span className="text-xs text-ink-400">Not added yet</span>}</div></div>})}</div>{!ready && <ButtonLink href="/counselling" variant="secondary" className="mt-4 w-full">Continue answering<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink>}</section>
        <Disclosure summary="Add more about yourself" hint="Optional"><div className="flex flex-wrap gap-2">{optional.map((q) => <Link key={q.key} href={`/counselling?edit=${q.key}`} className="cb-button border border-ink-200 bg-white px-3 py-2 text-xs text-forest-700 hover:bg-mint">{snapshot.answeredKeys.includes(q.key) ? "Edit " : "Add "}{optionalLabels[q.key]?.toLowerCase() ?? "a preference"}</Link>)}</div></Disclosure>
        <Callout tone="forest" title="Remember"><p>You are exploring possibilities, not choosing your whole future today.</p></Callout>
      </aside>

      <main className="order-1 min-w-0 lg:order-2" aria-labelledby="possibilities-title"><div className="mb-5 flex items-end justify-between gap-3"><div><Eyebrow>Your starting points</Eyebrow><h2 id="possibilities-title" className="mt-2 text-2xl font-semibold sm:text-3xl">What would you like to look into first?</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-ink-500">Choose the one that makes you curious. You can come back and explore the others later.</p></div><Link href="/counselling" className="hidden items-center gap-1 text-xs font-semibold text-forest-700 underline underline-offset-4 sm:flex"><Pencil aria-hidden className="h-3.5 w-3.5" />Change answers</Link></div>
        <div className="grid gap-4">{fields.map((suggestion, index) => <article key={suggestion.field.slug} className="group rounded-2xl border border-ink-200 bg-white p-5 transition-all duration-200 hover:-translate-y-0.5 hover:border-forest-300 hover:shadow-[0_16px_32px_-24px_#19382f80] sm:p-6"><div className="flex items-start gap-4"><span className={`grid h-14 w-14 shrink-0 place-items-center rounded-2xl ${accentSurface[fieldVisual(suggestion.field.slug).accent]}`}><FieldIcon slug={suggestion.field.slug} className="h-6 w-6" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-[.12em] text-ink-400">Possibility {index + 1}</span>{index === 0 && <Badge tone="green">A good place to start</Badge>}</div><h3 className="mt-1 text-xl font-semibold text-ink-900">{suggestion.field.name}</h3><p className="mt-2 text-sm leading-relaxed text-ink-600">{suggestion.field.tagline}</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-ink-100 pt-4"><p className="text-xs text-ink-500">Want to see what this could involve?</p><ButtonLink href={`/explore/${suggestion.field.slug}`} size="sm">Explore this<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink></div><details className="mt-3 rounded-xl bg-ink-50"><summary className="flex cursor-pointer items-center justify-between px-3 py-2.5 text-xs font-semibold text-ink-700">Why did this appear?<ChevronRight aria-hidden className="h-4 w-4" /></summary><div className="border-t border-ink-100 px-3 py-3 text-xs leading-relaxed text-ink-600">{suggestion.reasons.length ? <ul className="space-y-2">{suggestion.reasons.slice(0, 3).map((reason, i) => <li key={i}><span className="font-semibold text-forest-800">{FACTOR_LABELS[reason.factor]}:</span> {reason.detail}</li>)}</ul> : <p>This is a starting point to browse, not a conclusion about you.</p>}</div></details></article>)}</div>
        <div className="mt-5 rounded-2xl border border-dashed border-forest-300 bg-forest-50/70 p-5 sm:p-6"><h3 className="text-base font-semibold">Nothing feels right yet?</h3><p className="mt-2 text-sm leading-relaxed text-ink-600">That is okay. Browse the full set of areas, or talk through your thoughts with the mentor.</p><div className="mt-4 flex flex-wrap gap-2"><ButtonLink href="/explore" variant="secondary" size="sm">Browse all areas<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink><ButtonLink href="/mentor" variant="ghost" size="sm"><MessageCircle aria-hidden className="h-4 w-4" />Ask Mentor</ButtonLink></div></div>
        <Disclosure summary="See different ways to study later" hint={`${snapshot.stage === "class10" ? "After Class 10" : "After Class 12"}`}><p className="mb-4 text-sm leading-relaxed text-ink-600">Once you choose an area, we’ll help you look at courses, institutions and practical details together. For now, these are a few broad routes you may hear about.</p><div className="grid gap-2 sm:grid-cols-3">{paths.map(({ pathway }) => <Link key={pathway.slug} href={`/pathways/${pathway.slug}`} className="rounded-xl border border-ink-200 bg-white p-3 text-sm font-semibold text-ink-800 hover:border-forest-300 hover:bg-mint"><span className="block text-xs font-normal text-ink-500">A way to get there</span><span className="mt-1 block">{pathway.title}</span></Link>)}</div></Disclosure>
      </main>
    </div>
  </div>;
}
