import { notFound } from "next/navigation";
import { ArrowRight, Building2, ClipboardCheck, FileText, GraduationCap, MapPin, Navigation, Scale, ShieldCheck, Wallet } from "lucide-react";
import { Badge, BulletList, ButtonLink, Callout, Disclosure, SourceLink, VerificationBadge, formatDate } from "@/components/ui";
import { SaveButton } from "@/components/save-button";
import { DetailTabs } from "@/components/detail-tabs";
import { DetailHeader, LinkRow, NextStepPanel } from "@/components/detail-parts";
import { InstitutionMap } from "@/components/institution-map";
import { getAdmissionInfo, getCourses, getExams, getInstitution, getInstitutionLinks, getInstitutionSources, getInstitutions, getScholarships } from "@/services/catalog";
import { getSessionState } from "@/services/profile";
import { districtCentre, distanceLabel, mapSearchUrl } from "@/maps";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ code: string }> }) { return { title: (await getInstitution((await params).code))?.name ?? "Institution" }; }
export default async function InstitutionPage({ params }: { params: Promise<{ code: string }> }) {
  const institution = await getInstitution((await params).code); if (!institution) notFound();
  const [links, sources, admissions, allCourses, scholarships, state, nearby] = await Promise.all([getInstitutionLinks(institution.code), getInstitutionSources(institution.code), getAdmissionInfo(institution.code), getCourses({}), getScholarships({}), getSessionState(), getInstitutions({ district: institution.district })]);
  const offered = links.flatMap((link) => { const course = allCourses.find((c) => c.slug === link.courseSlug); return course ? [{ link, course }] : []; });
  const exams = await getExams({ slugs: [...new Set(offered.flatMap(({ course }) => course.examSlugs ?? []))] });
  const origin = districtCentre(state?.snapshot.district);
  const point = institution.latitude != null && institution.longitude != null ? { latitude: institution.latitude, longitude: institution.longitude } : null;
  const distance = distanceLabel(origin, point);
  const admission = admissions[0];
  const directions = mapSearchUrl(`${institution.name} ${institution.district} Nagaland`);
  const overview = <div className="space-y-5"><section className="cb-panel"><h2 className="cb-panel-title"><Building2 />Get to know the institution</h2><p className="cb-measure text-sm leading-relaxed text-ink-600">{institution.about ?? "The institution overview is currently unavailable."}</p><dl className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{[{ title: "Location", value: institution.city ?? institution.district }, { title: "Ownership", value: institution.ownership }, { title: "Hostel", value: institution.hostelAvailable === "unknown" ? "Not yet verified" : institution.hostelAvailable }, { title: "Admission status", value: institution.admissionStatus === "unknown" ? "Not yet verified" : institution.admissionStatus }, { title: "Study levels", value: (institution.studyLevels ?? []).join(", ").replace(/_/g, " ") || "Not listed" }, { title: "Distance", value: distance ?? "Set a district to see distance" }].map((fact) => <div key={fact.title} className="rounded-xl border border-ink-100 bg-canvas p-4"><dt className="text-xs font-semibold text-ink-500">{fact.title}</dt><dd className="mt-1.5 text-sm capitalize text-ink-800">{fact.value}</dd></div>)}</dl></section><InstitutionMap pins={[{ code: institution.code, name: institution.name, district: institution.district, latitude: institution.latitude, longitude: institution.longitude }]} origin={origin} originLabel={state?.snapshot.district} /></div>;
  const courseContent = <section className="cb-panel"><h2 className="cb-panel-title"><GraduationCap />Courses in our catalogue</h2><Callout tone="amber" title="Confirm programme availability"><p>These course links are sample data. Check the current prospectus before applying.</p></Callout><div className="mt-5 space-y-4">{offered.map(({ link, course }) => <div key={link.courseSlug}><LinkRow href={`/courses/${course.slug}`} title={course.name} description={course.durationLabel} icon={<GraduationCap className="h-4 w-4" />} accent="lavender" action="View eligibility" /><div className="mt-2 px-1"><VerificationBadge status={link.verificationStatus} lastVerifiedAt={link.lastVerifiedAt} /></div></div>)}</div>{!offered.length && <p className="mt-5 text-sm text-ink-500">No course list is available for this institution yet.</p>}</section>;
  const admissionContent = <div className="space-y-4"><section className="cb-panel"><h2 className="cb-panel-title"><ClipboardCheck />Before you apply</h2><VerificationBadge status={admission?.verificationStatus ?? "unavailable"} lastVerifiedAt={admission?.retrievedAt} /><p className="mt-4 max-w-prose text-sm text-ink-600">{admission?.applicationWindow ?? "CareerBridge could not verify the current application window. Read the official admission notice before making plans."}</p><div className="mt-5"><SourceLink href={institution.admissionPortal ?? institution.officialWebsite ?? admission?.sourceUrl}>Open admission source</SourceLink></div></section>
    <Disclosure summary="Application steps & required documents">{admission ? <div className="grid gap-6 md:grid-cols-2"><div><h3 className="mb-3 font-semibold">General process</h3><BulletList items={admission.process ?? []} /></div><div><h3 className="mb-3 font-semibold">Documents to prepare</h3><BulletList items={admission.documents ?? []} /></div></div> : <p>Application steps and documents are currently unavailable. Ask the institution for its current notice.</p>}</Disclosure>
    <Disclosure summary="Important dates & current notices"><p className="mb-4 text-sm">Current notices have not been verified.</p>{admission?.importantDates?.length ? <ul className="space-y-2">{admission.importantDates.map((date) => <li key={date.label}><strong>{date.label}: </strong>{date.value}</li>)}</ul> : <p>Dates are currently unavailable.</p>}{admission?.sourceUrl && <div className="mt-4"><SourceLink href={admission.sourceUrl} variant="inline">Read the official notice source</SourceLink></div>}</Disclosure>
    <Disclosure summary="Entrance exams linked to these courses"><div className="space-y-3">{exams.map((e) => <LinkRow key={e.slug} href={`/exams#${e.slug}`} title={e.shortName ?? e.name} icon={<FileText className="h-4 w-4" />} action="See exam" />)}{!exams.length && <p>No entrance exam is linked in this sample catalogue. Confirm the requirement for your course.</p>}</div></Disclosure></div>;
  const fees = <div className="space-y-4"><section className="cb-panel"><h2 className="cb-panel-title"><Wallet />Fees & living costs</h2><p className="text-sm leading-relaxed text-ink-600">{institution.feeRangeNote ?? "Current fees are unavailable. Ask about tuition, hostel, deposits, travel and other costs."}</p><div className="mt-5"><SourceLink href={institution.officialWebsite}>Check official fee information</SourceLink></div></section><Disclosure summary="Scholarship schemes to explore"><div className="space-y-3">{scholarships.map((s) => <LinkRow key={s.slug} href={`/scholarships#${s.slug}`} title={s.name} icon={<Wallet className="h-4 w-4" />} accent="butter" action="Check scheme" />)}</div></Disclosure></div>;
  const sourceContent = <section className="cb-panel"><h2 className="cb-panel-title"><ShieldCheck />Sources & contact</h2><VerificationBadge status={institution.verificationStatus} lastVerifiedAt={institution.lastVerifiedAt} /><div className="mt-5 flex flex-wrap gap-3"><SourceLink href={institution.officialWebsite}>Official website</SourceLink>{institution.admissionPortal && <SourceLink href={institution.admissionPortal} variant="secondary">Admission portal</SourceLink>}</div><div className="mt-6 space-y-4">{sources.map((source) => <div key={source.id} className="rounded-xl border border-ink-200 bg-canvas p-4"><p className="mb-2 text-sm font-semibold">{source.title ?? "Institution source"}</p><SourceLink href={source.url} variant="inline">Open source</SourceLink><p className="mt-2 text-xs text-ink-500">{source.retrievedAt ? `Last retrieved ${formatDate(source.retrievedAt)}` : "Not yet checked"} · {source.status}</p></div>)}{!sources.length && <p className="text-sm text-ink-500">No additional source has been recorded yet.</p>}</div><div className="mt-6 border-t border-ink-100 pt-5"><h3 className="mb-2 text-sm font-semibold">Contact details</h3>{institution.contactEmail ? <a href={`mailto:${institution.contactEmail}`} className="cb-source text-sm">{institution.contactEmail}</a> : <p className="text-sm text-ink-500">Email currently unavailable</p>}{institution.contactPhone && <p className="mt-2 text-sm">Phone: {institution.contactPhone}</p>}</div></section>;
  return <div className="cb-container cb-page"><DetailHeader eyebrow="Institutions in Nagaland" title={institution.name} description={`${institution.city ?? institution.district}, ${institution.district} district`} icon={<Building2 className="h-6 w-6" />} accent="sky" facts={<><Badge tone="forest">{institution.type}</Badge><Badge>{institution.ownership}</Badge><Badge tone="amber">Sample data · needs verification</Badge></>} actions={<><SourceLink href={institution.officialWebsite}>Visit official website</SourceLink><SaveButton itemType="institution" itemRef={institution.code} label={institution.name} /><SourceLink href={directions} variant="secondary"><Navigation aria-hidden className="h-4 w-4" />Directions</SourceLink><ButtonLink href={`/compare?type=institution&a=${institution.code}`} variant="secondary"><Scale aria-hidden className="h-4 w-4" />Compare</ButtonLink></>} />
    <div className="cb-detail-content"><DetailTabs tabs={[{ id: "overview", label: "At a glance", content: overview }, { id: "courses", label: "Courses", content: courseContent }, { id: "admission", label: "Admissions", content: admissionContent }, { id: "fees", label: "Fees & support", content: fees }, { id: "sources", label: "Sources", content: sourceContent }]} /><aside className="cb-detail-aside"><NextStepPanel title="Keep the next steps together." text="Check eligibility and fees, get documents ready, and follow the official admission notice." href={`/action-plan?focus=institution:${institution.code}`} cta="Add to my action plan" /><Disclosure summary={`More in ${institution.district}`}><div className="space-y-3">{nearby.filter((i) => i.code !== institution.code).map((i) => <LinkRow key={i.code} href={`/institutions/${i.code}`} title={i.name} icon={<MapPin className="h-4 w-4" />} action="View" />)}{nearby.length <= 1 && <p>No more institutions are listed in this district yet.</p>}</div></Disclosure></aside></div>
  </div>;
}
