import { notFound } from "next/navigation";
import { ArrowRight, BookOpen, Building2, ClipboardCheck, GraduationCap, Lightbulb, Scale, ShieldCheck, Wallet, FileText } from "lucide-react";
import { Badge, BulletList, ButtonLink, Callout, Disclosure, SourceLink, VerificationBadge } from "@/components/ui";
import { DetailTabs } from "@/components/detail-tabs";
import { DetailHeader, LinkRow, MiniJourney, NextStepPanel, NoCatalogItems } from "@/components/detail-parts";
import { levelLabelSafe } from "@/components/course-helpers";
import { SaveButton } from "@/components/save-button";
import { WorkspacePage } from "@/components/journey-workspace";
import { getCourse, getCourses, getExams, getField, getInstitutionsForCourse, getScholarships } from "@/services/catalog";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { return { title: (await getCourse((await params).slug))?.name ?? "Course" }; }
export default async function CoursePage({ params }: { params: Promise<{ slug: string }> }) {
  const course = await getCourse((await params).slug); if (!course) notFound();
  const [institutions, exams, field, scholarships, siblings] = await Promise.all([getInstitutionsForCourse(course.slug), getExams({ slugs: course.examSlugs ?? [] }), course.fieldSlug ? getField(course.fieldSlug) : Promise.resolve(null), getScholarships({}), getCourses({ fieldSlug: course.fieldSlug ?? undefined })]);
  const overview = <div className="space-y-5">
    <section className="cb-panel"><h2 className="cb-panel-title"><ClipboardCheck />What do I need to apply?</h2><VerificationBadge status={course.verificationStatus} lastVerifiedAt={course.lastVerifiedAt} /><p className="cb-measure mt-4 text-base leading-relaxed text-ink-600">{course.eligibility}</p><p className="mt-3 text-xs text-ink-500">This is a general course outline. Confirm the current eligibility on the institution’s official site.</p>
      <div className="mt-6 border-t border-ink-100 pt-5"><h3 className="mb-2 text-sm font-semibold">Entrance requirements</h3><p className="cb-measure text-sm leading-relaxed text-ink-600">{course.entranceRequirement ?? "Currently unavailable."}</p></div>
    </section>
    <div className="grid gap-4 sm:grid-cols-2"><section className="rounded-xl border border-sky-ink/20 bg-sky/40 p-5"><h3 className="cb-panel-title"><BookOpen />Helpful subjects</h3><div className="flex flex-wrap gap-2">{(course.relevantSubjects ?? []).map((s) => <Badge key={s}>{s}</Badge>)}</div></section><section className="rounded-xl border border-lavender-ink/20 bg-lavender/30 p-5"><h3 className="cb-panel-title"><Lightbulb />Directions to explore</h3><BulletList items={course.careerDirections ?? []} /></section></div>
    <Disclosure summary="What can I study afterwards?"><BulletList items={course.furtherStudy ?? []} /></Disclosure>
  </div>;
  const colleges = <section className="cb-panel"><h2 className="cb-panel-title"><Building2 />Institutions to look into</h2><Callout tone="amber"><p>Sample course links. Confirm that the programme is currently offered before applying.</p></Callout><div className="mt-5 space-y-3">{institutions.map((i) => <LinkRow key={i.code} href={`/institutions/${i.code}`} title={i.name} description={`${i.district} · ${i.ownership}`} icon={<Building2 className="h-4 w-4" />} accent="sky" action="View" />)}{!institutions.length && <NoCatalogItems href="/institutions" label="Browse institutions" />}</div><div className="mt-6"><ButtonLink href={`/institutions?course=${course.slug}`}>Search institutions<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink></div></section>;
  const funding = <div className="space-y-4"><section className="cb-panel"><h2 className="cb-panel-title"><Wallet />Fees & support</h2><VerificationBadge status={course.feeNote ? course.verificationStatus : "unavailable"} lastVerifiedAt={course.lastVerifiedAt} /><p className="mt-4 text-sm leading-relaxed text-ink-600">{course.feeNote ?? "Current fees have not been verified. Check tuition, hostel and travel costs with the institution."}</p>{course.sourceUrl && <SourceLink href={course.sourceUrl} className="mt-5">Check official fees</SourceLink>}</section><section className="cb-panel"><h2 className="cb-panel-title"><GraduationCap />Scholarship portals to check</h2><p className="mb-4 text-xs text-ink-500">Eligibility differs by scheme. These are links to explore, not eligibility confirmations.</p><div className="space-y-3">{scholarships.slice(0, 3).map((s) => <LinkRow key={s.slug} href={`/scholarships#${s.slug}`} title={s.name} icon={<Wallet className="h-4 w-4" />} accent="butter" action="Check scheme" />)}</div></section></div>;
  const reflect = <div className="space-y-4"><Disclosure summary="Why might this course NOT be right for me?" tone="amber"><BulletList items={["Check the actual subjects, workload and duration — not only the course name.", ...(field?.challenges ?? []), "Budget for travel and accommodation alongside tuition."]} /></Disclosure><Disclosure summary="What if I don’t qualify?"><p>Different institutions and courses have different requirements. Look at related programmes and ask about legitimate diploma or later-entry routes.</p></Disclosure><section className="cb-panel"><h2 className="cb-panel-title"><Scale />Compare a related course</h2><div className="space-y-3">{siblings.filter((c) => c.slug !== course.slug).map((c) => <LinkRow key={c.slug} href={`/compare?type=course&a=${course.slug}&b=${c.slug}`} title={c.name} description={c.durationLabel} icon={<Scale className="h-4 w-4" />} accent="lavender" action="Compare" />)}</div></section></div>;
  const sources = <section className="cb-panel"><h2 className="cb-panel-title"><ShieldCheck />Sources & entrance exams</h2><VerificationBadge status={course.verificationStatus} lastVerifiedAt={course.lastVerifiedAt} /><p className="my-4 max-w-prose text-sm text-ink-600">{course.sourceUrl ? "Open the source to check current requirements." : "This is a general CareerBridge course outline. Institution-specific requirements and fees are not yet verified."}</p>{course.sourceUrl && <SourceLink href={course.sourceUrl}>Open course source</SourceLink>}<div className="mt-6 space-y-3">{exams.map((e) => <LinkRow key={e.slug} href={`/exams#${e.slug}`} title={e.shortName ?? e.name} description="See requirements and official examination portal" icon={<FileText className="h-4 w-4" />} accent="sky" action="Open" />)}{!exams.length && <p className="text-sm text-ink-500">No examination is linked in our catalogue. Check the institution’s current requirements.</p>}</div></section>;
  return <WorkspacePage active="study"><div className="mb-5"><MiniJourney current={2} /></div>
    <DetailHeader eyebrow="Explore a course" title={course.name} icon={<GraduationCap className="h-6 w-6" />} accent="lavender" facts={<><Badge tone="lavender">{levelLabelSafe(course.level)}</Badge>{course.durationLabel && <Badge>{course.durationLabel}</Badge>}<VerificationBadge status={course.verificationStatus} lastVerifiedAt={course.lastVerifiedAt} /></>} actions={<><ButtonLink href={`/institutions?course=${course.slug}`}>Find institutions<ArrowRight aria-hidden className="h-4 w-4" /></ButtonLink><SaveButton itemType="course" itemRef={course.slug} label={course.name} /><ButtonLink href={`/compare?type=course&a=${course.slug}`} variant="secondary"><Scale aria-hidden className="h-4 w-4" />Compare course</ButtonLink></>} />
    <div className="cb-detail-content"><DetailTabs tabs={[{ id: "overview", label: "At a glance", content: overview }, { id: "institutions", label: "Where to study", content: colleges }, { id: "fees", label: "Fees & support", content: funding }, { id: "reflect", label: "Alternatives", content: reflect }, { id: "sources", label: "Sources", content: sources }]} /><aside className="cb-detail-aside"><NextStepPanel title="Make this a practical plan." text="Check eligibility, shortlist institutions, and prepare your documents — one step at a time." href={`/action-plan?focus=course:${course.slug}`} cta="Build an action plan" mentorQuestion={`Help me think through ${course.name} and its alternatives.`} /><Callout tone="amber" title="Check before applying"><p>Course outlines are not current admission guarantees. Always confirm with the institution.</p></Callout></aside></div>
  </WorkspacePage>;
}
