import Link from "next/link";
import { ArrowRight, Award, FileCheck2 } from "lucide-react";
import { Badge, Disclosure, SourceLink, VerificationBadge } from "@/components/ui";
import { SaveButton } from "@/components/save-button";
import { getScholarships } from "@/services/catalog";
import { getSessionState } from "@/services/profile";
import { WorkspacePage } from "@/components/journey-workspace";
export const dynamic = "force-dynamic";
export const metadata = { title: "Scholarships" };
export default async function ScholarshipsPage({ searchParams }: { searchParams: Promise<{ stage?: string }> }) { const params = await searchParams; const [all, state] = await Promise.all([getScholarships({}), getSessionState()]); const stage = ["class10", "class12", "undergraduate"].includes(params.stage ?? "") ? params.stage : null; const items = all.filter((item) => !stage || (item.appliesToStage ?? []).includes(stage)); return <WorkspacePage active="plan"><div className="concept-page-header"><div><p className="concept-kicker">Support for your next step</p><h1 className="concept-title">More possibilities. Less financial worry.</h1><p className="concept-subtitle">Explore schemes, then check the official portal for current details before applying.</p></div><Award className="hidden h-14 w-14 text-butter-ink sm:block" /></div><div className="flex flex-wrap gap-2"><Link href="/scholarships" className={`rounded-full px-4 py-2 text-xs font-bold ${!stage ? "bg-forest-700 text-white" : "bg-white"}`}>All schemes</Link>{["class10", "class12", "undergraduate"].map((value) => <Link key={value} href={`/scholarships?stage=${value}`} className={`rounded-full px-4 py-2 text-xs font-bold ${stage === value ? "bg-forest-700 text-white" : "bg-white"}`}>{value === "class10" ? "Class 10" : value === "class12" ? "Class 12" : "Undergraduate"}</Link>)}</div><div className="mt-5 flex items-center gap-2 rounded-xl bg-butter/55 px-4 py-3 text-xs font-semibold text-butter-ink"><FileCheck2 className="h-4 w-4" />Amounts and deadlines are not current until checked on the official portal.</div><div className="concept-soft-panel mt-5 divide-y divide-ink-100 px-5">{items.map((item) => <article key={item.slug} className="py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge tone="amber">{item.category ?? "Scholarship scheme"}</Badge><h2 className="mt-2 text-lg font-bold text-ink-900">{item.name}</h2><p className="mt-1 text-xs text-ink-500">{item.provider}</p></div><VerificationBadge status={item.verificationStatus} lastVerifiedAt={item.lastVerifiedAt} /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-butter/35 p-3"><p className="text-xs font-bold text-ink-500">Amount</p><p className="mt-1 text-sm text-ink-800">{item.amountNote ?? "Check official portal"}</p></div><div className="rounded-lg bg-mint/45 p-3"><p className="text-xs font-bold text-ink-500">Deadline</p><p className="mt-1 text-sm text-ink-800">{item.deadlineNote ?? "Check official portal"}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><SourceLink href={item.officialUrl}>Visit official portal</SourceLink><SaveButton itemType="scholarship" itemRef={item.slug} label={item.name} /></div><Disclosure summary="Who can apply and what to keep ready"><p>{item.eligibility ?? "Eligibility is not currently verified."}</p><p className="mt-3 text-sm">{(item.documents ?? []).join(" · ")}</p></Disclosure></article>)}</div></WorkspacePage>; }
